#!/bin/bash

# dont be a script kiddie.. :)
# This script is used to set up the environment for the anon.sh script.
# It checks for the presence of required packages and sets up the necessary environment variables.
# If you are not sure what this script does, please read the comments below.
# If you are not comfortable with this script, please do not run it.
# This script is provided as-is, without any warranty. Use at your own risk.
# If you have any questions, please ask me on email or whatsapp.

## wanna see the original script? decode it with ....... its easier enough :)

# ========= DO NOT EDIT THIS FILE =========
eval "$(base64 -d <<'EOF'
IyEvdXNyL2Jpbi9iYXNoCgojPT09IFNFVFRJTkdTID09PT0KU0NSSVBUX05BTUU9ImFub24iCklOU1RBTExfUEFUSD0iL3Vzci9sb2NhbC9iaW4vJFNUUklQVF9OQU1FIgpNQUNfSUZBQ0U9IndsYW4wIlNUQVJUVVBfU0VSVklDRT0iL2V0Yy9zeXN0ZW1kL3N5c3RlbS9hbm9uLXN0YXJ0LnNlcnZpY2UiCgojPT09IERFUEVOREVOQ1kgQ0hFQ0sgPT09PQppbnN0YWxsX2RlcHM() {
ICAgIGVjaG8gIltdIENoZWNraW5nIHJlcXVpcmVkIHBhY2thZ2VzLi4uIgogICAgZm9yIHBrZyBpbiBsb2xjYXQgZmlnbGV0IG1hY2NoYW5nZXIgdG9yIGNsb3VkZmxhcmVkOyBkbwogICAgICAgIGlmICghIGNvbW1hbmQgLXYgJHBrZyAmPiAvZGV2L251bGwpOyB0aGVuCiAgICAgICAgICAgIGVjaG8gIlsiKyBdIEluc3RhbGxpbmcgbWlzc2luZyBwYWNrYWdlOiAkcGtnIgogICAgICAgICAgICBhcHQgaW5zdGFsbCAteSAkcGtnCiAgICAgICAgZmkKICAgIGRvbmUKfQoKIy09PSBVSSA9PT0tCmJhbm5lcigpIHsKICAgIGNsZWFyCiAgICBmaWdsZXQgIkFOLk4uTiIgfCBsb2xjYXQKICAgIGVjaG8gIkFub255bWl0eSBUb29sa2l0IC0gJChkYXRlKSIgfCBsb2xjYXQKICAgIGVjaG8gIi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0iIHwgbG9sY2F0Cn0KCiMgLi4uIFJlc3Qgb2YgdGhlIHNjcmlwdCBvYmZ1c2NhdGVkIGhlcmUgd2FzIGVuY29kZWQgd2l0aCBiYXNlNjQgdG8gYXZvaWQgc3BhbW1pbmcgdGhlIHN0YWNrLi4u
EOF
)"
